CREATE DATABASE IF NOT EXISTS web2;
USE web2;


CREATE TABLE IF NOT EXISTS usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
password VARCHAR(255) DEFAULT NULL,
creado_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;